language: node_js

node_js:
  - node

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

after_script:
  - cd dist
  - git init
  - git config --global user.name 'xLsDg'
  - git config --global user.email 'xlsdg@qq.com'
  - git add .
  - git commit -m "Update demo"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

env:
  global:
    - GH_REF: github.com/xlsdg/user-dashboard.git
    - secure: "Sah1E0ikBqpdJan5HcorOihT//tw3we1nOPqXKrPRNJIcWE2LFPcQNwWu07LMEGba5ak7I3bxSFOJUW4UUBwUxwBO518eDVTZFW3RKYLBS7ELXnVRK5ACJusiaL2/l2I9K6nMNxA3f2X4fff3At5RjVpFffEh5hc9h08ZXS5bn9yno4+hSz8Up6nO00V/b3rRSly/IwcCrWUJ3OxkCjf3buOsnWRVVwBRx54oC1ndKVWWB4s+30CpIYgCmD4lJ3JQ5RofvBGp0SOqMzySd/RuQpVYjrY+8FpQGMRGrugwQ8ikBkB7ml5l5v75DRFh/p1gHqrEl+gFb36JvNw8CxvkfMoQQmBxD8CeE/7L0ZxfM2hG/ygK6Ighm3JAGvYT/PIvF8xMWSc8ltsZgtkyL1USkz/0muxonRkt1yQW+wwykA4goO82FM6wXMJ83EQYCm0Kp8mAXl/FaABeoSwICiWIofTucg8H3A4Dr1UWF4KQ8eXH60skK0XjclF+ZMiokGsl7BcyIsxgPzCbU9DHb80DYfyCPDwV9hzTvkP+zdEPZnb+E/wiVePHBJpJVG9uMxWrrKN8OYcWvMJH9U9tDvfFxxoEvWmpjMW5N63Q/OwCy5O+rl614B5f3UYieDVVZzbn9mTjGY9Egiy6+116GDKJucoGdB7pGRUlMScyjON4C4="
